install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - appveyor DownloadFile https://github.com/nats-io/nats-streaming-server/releases/download/v0.3.8/nats-streaming-server-v0.3.8-windows-amd64.zip
  - 7z e nats-streaming-server-v0.3.8-windows-amd64.zip nats-streaming-server-v0.3.8.exe -r -oc:\projects\nss\build
  - cmd: ren C:\projects\nss\build\nats-streaming-server-v0.3.8.exe nats-streaming-server.exe
  - cmd: set PATH=%PATH%;C:\projects\nss\build
before_build:
  - nuget restore
build:
  project: STAN.sln
notifications:
  - provider: GitHubPullRequest
    auth_token:
      secure: iVXvp6gJv5IQjqJRZJCXVw==
    template: "{{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})"
